config/routes.rb
MobileTest::Application.routes.draw do
  get "password_resets/new"

  root :to => 'homes#log_in', :as => "log_in" 
  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "menu" => "homes#menu", :as => "menu" 
  
  resources :posts
  resources :comments do
    get 'checked', :on => :member
  end
    
  resources :sessions
  resources :dashboards
  resources :guidepdfs
  resources :guidenotes
  resources :guidedownloads
  resources :standards
  resources :standardsubsections
  
  resources :sections
  resources :subsections
  resources :clauses do
    get 'show_guide', :on =>:member
    get 'delete_guidenote', :on =>:member
    get 'clone_subsection', :on =>:member
    get 'clone_clause', :on =>:member
    get 'edit_guidenote', :on =>:member
  end
  resources :guidenotes do
      get 'single_edit', :on =>:member
  end
  resources :txt3s
  resources :txt4s
  resources :txt5s
  resources :clausetitles
  
  resources :templates do
    collection do
      post "import"
      get "export"
    end
  end
  
  resources :activities
  resources :admins do
    get 'change', :on => :member
  end      
  
  resources :users do
    get 'unlock', :on => :member
  end
  resources :accounts do
    get 'add_licence', :on => :member
    get 'minus_licence', :on => :member
  end  

  resources :sponsors
  resources :suppliers

  resources :password_resets

  resources :exports do 
    get :clausetype_4_download, :on => :member
    get :clausetype_5_download, :on => :member
    get :linetype_change, :on => :member
    get :clausetype_update, :on => :member
  end

end

app/views/admins/index.html.erb
<div data-role="header">
  <%= link_to "log out", log_out_path, "data-theme"=>"b" %>
  <h1>Select Company</h1>
  <h4>Current company: <%= @user.company.company_name %></h4>
	<%= link_to "Menu", menu_path, "data-theme"=>"b" %>	
</div>

<div data-role="content">
	<ul data-role="listview" data-inset="true">

		<% @companies.each do |company| %>
    		<li data-icon="arrow">   			    	    		
				<%= link_to change_admin_path(company.id) do %>          		
					<h3><%= company.company_name  %></h3>
				<% end %> 
			</li>						
		<% end %> 
	</ul>
</div>