config/routes.rb
MobileTest::Application.routes.draw do
  get "password_resets/new"

  root :to => 'homes#log_in', :as => "log_in" 
  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "menu" => "homes#menu", :as => "menu" 
  
  resources :posts
  resources :comments do
    get 'checked', :on => :member
  end
    
  resources :sessions
  resources :dashboards
  resources :guidepdfs
  resources :guidenotes
  resources :guidedownloads
  resources :standards
  resources :standardsubsections
  
  resources :sections
  resources :subsections
  resources :clauses do
    get 'show_guide', :on =>:member
    get 'delete_guidenote', :on =>:member
    get 'clone_subsection', :on =>:member
    get 'clone_clause', :on =>:member
    get 'edit_guidenote', :on =>:member
  end
  resources :guidenotes do
      get 'single_edit', :on =>:member
  end
  resources :txt3s
  resources :txt4s
  resources :txt5s
  resources :clausetitles
  
  resources :templates do
    collection do
      post "import"
      get "export"
    end
  end
  
  resources :activities
  resources :admins do
    get 'change', :on => :member
  end      
  
  resources :users do
    get 'unlock', :on => :member
  end
  resources :accounts do
    get 'add_licence', :on => :member
    get 'minus_licence', :on => :member
  end  

  resources :sponsors
  resources :suppliers

  resources :password_resets

  resources :exports do 
    get :clausetype_4_download, :on => :member
    get :clausetype_5_download, :on => :member
    get :linetype_change, :on => :member
    get :clausetype_update, :on => :member
  end

end

app/models/clausetitle.rb
class Clausetitle < ActiveRecord::Base

#associations
has_many :clauses
  


end

app/controllers/clausetitles_controller.rb
class ClausetitlesController < ApplicationController

before_filter :require_user

  # GET /clausetitles
  # GET /clausetitles.json
  def index
    
    used_clausetitle_id_array = Clause.all.collect{|i| i.clausetitle_id}.uniq
    clausetitle_id_array = Clausetitle.all.collect{|i| i.id}.uniq    
    
    unused_clausetitle_id_array = clausetitle_id_array - used_clausetitle_id_array

    @clausetitles = Clausetitle.includes(:clauses).where(:id => unused_clausetitle_id_array)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clausetitles }
    end
  end

  # DELETE /clausetitles/1
  # DELETE /clausetitles/1.json
  def destroy
    @clausetitle = Clausetitle.find(params[:id])
    @clausetitle.destroy

    respond_to do |format|
      format.html { redirect_to clausetitles_url }
      format.json { head :ok }
    end
  end
end

app/views/clausetitles/index.html.erb
<div data-role="header">
	  <%= link_to "log out", log_out_path %>
	<h1>Clause Titles</h1>
		<%= link_to "Menu", menu_path %>	
</div>

<div data-role="content">
	<ul data-role="listview" data-inset="true" class="custom_list" >

<% @clausetitles.each do |clausetitle| %>
    			<li>   			    	    		
					<div id="text_content" style="width:500px; font-size:11px">
						<%= clausetitle.text %>	
					</div>
					       
						<span class="ui-li-count" style="color: #FFFFFF; background: #00507f; font-size:11px;"><%= clausetitle.clauses.count %></span>
 					<div> 
 						<%= link_to '', clausetitle_path(clausetitle), {:confirm => 'Are you sure?', :method => :delete, "data-role"=>"button", "data-inline"=>"true", "data-icon" => "delete", "data-iconpos"=>"notext", "data-theme"=> "c"}%>          		
					</div> 		
				</li>						
<% end %> 
	</ul>
</div>